print("----- PERSONAL BIODATA -----")
print("Name       : Gaurav Kinkar")
print("Age        : 20")
print("Gender     : male")
print("Address    : Wardha, Maharashtra")
print("College    : GCE KARAD ")
print("Branch     : Information Technology")
print("Contact No : 7464xxxxxx")
print("Email      : gk@gmail.com")
